personal-blog/Controllers/LayoutController.cs
using PagedList;
using personal_blog.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace personal_blog.Controllers
{

    [AllowAnonymous]

    public class LayoutController : Controller
    {

        Context db = new Context();

        public PartialViewResult Carousel()
        {
            var values = db.Posts.Where(x => x.Status == true && x.Category.Status == true).OrderByDescending(x => x.ID).Take(3).ToList();
            return PartialView(values);
        }

        public PartialViewResult NavbarCategories()
        {
            var values = db.Categories.Where(x => x.Status == true).OrderBy(x => x.Name).ToList();
            return PartialView(values);
        }

        public PartialViewResult NavbarAccounts()
        {
            var values = db.Accounts.Where(x => x.Status == true && x.Icon.Status == true).ToList();
            return PartialView(values);
        }

        public PartialViewResult FooterAboutUs()
        {
            var values = db.Abouts.ToList();
            return PartialView(values);
        }

        public PartialViewResult FooterLatestPosts()
        {
            var values = db.Posts.Where(x => x.Status == true && x.Category.Status == true).OrderBy(x => x.ID).Take(3).ToList();
            return PartialView(values);
        }

        public PartialViewResult FooterAccounts()
        {
            var values = db.Accounts.Where(x => x.Status == true && x.Icon.Status == true).ToList();
            return PartialView(values);
        }

    }
}

personal-blog/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en">

<head>
    <title>Admin - Personal Blog</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="description" content="Boyut Endüstriyel Stok Yönetim Paneli">
    <meta name="author" content="Boyut Endüstriyel">

    <link rel="icon" href="~/Templates/admin-template/logo.ico" type="image/x-icon">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="/Templates/admin-template/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/Templates/admin-template/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/Templates/admin-template/assets/vendor/animate-css/vivify.min.css">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="/Templates/admin-template/assets/css/mooli.min.css">

</head>
<body>

    <div id="body" class="theme-cyan">

        <!-- Overlay For Sidebars -->
        <div class="overlay"></div>

        <div id="wrapper">

            <!-- Page top navbar -->
            <nav class="navbar navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-left">
                        <div class="navbar-btn">
                            <a href="/Beyanname/Index">@*<img src="~/Templates/admin-template/kaptan-logo-removebg-preview.png" alt="logo" class="img-fluid logo">*@</a>
                            <button type="button" class="btn-toggle-offcanvas"><i class="fa fa-align-left"></i></button>
                        </div>
                        <form id="navbar-search" class="navbar-form search-form">
                            <button type="button" class="btn btn-default"><i class="fa fa-search"></i></button>
                            <input value="" class="form-control" placeholder="Ara..." type="text">
                        </form>
                    </div>
                    <div class="navbar-right">
                        <div id="navbar-menu">
                            <ul class="nav navbar-nav">
                                <li class="hidden-xs" style="display: none;"><a href="javascript:void(0);" id="btnFullscreen" class="icon-menu"><i class="fa fa-arrows-alt"></i></a></li>
                            </ul>
                        </div>
                        <div class="d-flex justify-content-center align-items-center mr-2">
                            <span id="clock" class="align-items-center"></span>
                        </div>
                        <a href="/Admin/UserDetails/@Session["UserId"]" title="Menüye Dön" class="text-dark font-20 mx-3"><i class="fa fa-user"></i></a>
                        <a href="/Login/SignOut" title="Menüye Dön" class="text-dark font-20"><i class="fa fa-sign-out"></i></a>
                    </div>
                </div>
            </nav>

            <!-- Main left sidebar menu -->
            <div id="left-sidebar" class="sidebar">
                <div class="navbar-brand text-center">
                    <a href="/Admin/Index">@*<img src="~/Templates/admin-template/kaptan-logo-layout.png" alt="Mooli Logo" class="img-fluid logo">*@<span>Personal Blog</span></a>
                    <button type="button" class="btn-toggle-offcanvas btn btn-sm float-right"><i class="lnr lnr-menu fa fa-chevron-circle-left"></i></button>
                </div>
                <div class="sidebar-scroll">
                    <nav id="left-sidebar-nav" class="sidebar-nav">
                        <ul id="main-menu" class="metismenu animation-li-delay">

                            <li class="header text-center pb-3">MENÜ</li>

                            <li><a href="/Admin/Index"><i class="fa fa-home"></i> <span>Home</span> </a></li>

                            <li class="mb-2">
                                <a href="" class="has-arrow"><i class="fa fa-pencil-square-o"></i><span>Post</span></a>
                                <ul>
                                    <li><a href="/Admin/Posts">Posts</a></li>
                                    <li><a href="/Admin/Categories">Categories</a></li>
                                </ul>
                            </li>

                            <li class="mb-2">
                                <a href="" class="has-arrow"><i class="fa fa-file"></i><span>Pages &amp; Cards</span></a>
                                <ul>
                                    <li><a href="/Admin/About">About</a></li>
                                    <li><a href="/Admin/Author">Author</a></li>
                                </ul>
                            </li>

                            <li class="mb-2">
                                <a href="" class="has-arrow"><i class="fa fa-th-large"></i><span>Other</span></a>
                                <ul>
                                    <li><a href="/Admin/Messages">Messages</a></li>
                                    <li><a href="/Admin/Accounts">Accounts</a></li>
                                </ul>
                            </li>

                        </ul>
                    </nav>
                </div>
            </div>

            <!-- Main body part  -->
            <div id="main-content">
                <div class="container-fluid">
                    <div class="row clearfix">

                        <div class="col-lg-12 col-md-12">
                            <div class="card planned_task">
                                <div class="header">
                                    <ul class="header-dropdown dropdown">
                                        <li><a href="javascript:void(0);" class="full-screen"><i class="fa fa-expand"></i></a></li>
                                    </ul>
                                </div>
                                <div class="body">
                                    @RenderBody()
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>

    </div>
    <!-- Javascript -->
    <script src="/Templates/admin-template/assets/bundles/libscripts.bundle.js"></script>
    <script src="/Templates/admin-template/assets/bundles/vendorscripts.bundle.js"></script>

    <!-- Vedor js file and create bundle with grunt  -->
    <!-- Project core js file minify with grunt -->
    <script src="/Templates/admin-template/assets/bundles/mainscripts.bundle.js"></script>

    <script>

        function clock() {
            var clock = document.getElementById('clock');
            clock.innerText = new Date().toLocaleString();
        }

        setInterval(clock, 1000);

    </script>

</body>
</html>

personal-blog/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>Personal Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300, 400,700|Inconsolata:400,700" rel="stylesheet">

    <link rel="stylesheet" href="~/Templates/template/css/bootstrap.css">
    <link rel="stylesheet" href="~/Templates/template/css/animate.css">
    <link rel="stylesheet" href="~/Templates/template/css/owl.carousel.min.css">

    <link rel="stylesheet" href="~/Templates/template/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Templates/template/fonts/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Templates/template/fonts/flaticon/font/flaticon.css">

    <!-- Theme Style -->
    <link rel="stylesheet" href="~/Templates/template/css/style.css">

    <style>
        .active {
            font-weight: 600;
        }
    </style>
</head>
<body>


    <div class="wrap">

        <header role="banner">
            <div class="top-bar">
                <div class="container">
                    <div class="row">
                        @Html.Action("NavbarAccounts", "Layout")
                        <div class="col-3 search-top">
                            <!-- <a href="#"><span class="fa fa-search"></span></a> -->
                            <form action="/Home/Index" class="search-top-form">
                                <span class="icon fa fa-search"></span>
                                <input type="text" id="s" name="search" placeholder="Search posts.." >
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container logo-wrap">
                <div class="row pt-5">
                    <div class="col-12 text-center">
                        <a class="absolute-toggle d-block d-md-none" data-toggle="collapse" href="#navbarMenu" role="button" aria-expanded="false" aria-controls="navbarMenu"><span class="burger-lines"></span></a>
                        <h1 class="site-logo"><a href="/Home/Index">Personal Blog</a></h1>
                    </div>
                </div>
            </div>

            <nav class="navbar navbar-expand-md  navbar-light bg-light">
                <div class="container">


                    <div class="collapse navbar-collapse" id="navbarMenu">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a id="home" class="nav-link" href="/Home/Index">Home</a>
                            </li>
                            @Html.Action("NavbarCategories", "Layout")
                            <li class="nav-item">
                                <a id="about" class="nav-link" href="/About/Index">About</a>
                            </li>
                            <li class="nav-item">
                                <a id="contact" class="nav-link" href="/Contact/Index">Contact</a>
                            </li>
                        </ul>

                    </div>
                </div>
            </nav>
        </header>
        <!-- END header -->
        <!-- END section -->

        <section class="site-section py-sm">
            <div class="container">
                <div class="row blog-entries">

                    @RenderBody()

                    <!-- END main-content -->

                    <div class="col-md-12 col-lg-4 sidebar py-5">
                        <div class="sidebar-box search-form-wrap">
                            <form action="/Home/Index" class="search-form">
                                <div class="form-group">
                                    <span class="icon fa fa-search"></span>
                                    <input type="text" class="form-control" name="search" id="s" placeholder="Search posts..">
                                </div>
                            </form>
                        </div>
                        <!-- END sidebar-box -->

                        @Html.Action("Author", "Home")

                        <!-- END sidebar-box -->

                        @Html.Action("PopularPosts", "Home")

                        <!-- END sidebar-box -->

                        @Html.Action("Categories", "Home")

                        <!-- END sidebar-box -->

                    </div>
                    <!-- END sidebar -->

                </div>
            </div>
        </section>

        <footer class="site-footer">
            <div class="container">
                <div class="row mb-5 justify-content-between">
                    @Html.Action("FooterAboutUs", "Layout")
                    <div class="col-md-6">
                        <div class="row">
                            @Html.Action("FooterLatestPosts", "Layout")
                            <div class="col-md-1"></div>

                            <div class="col-md-4">

                                <div class="mb-5">
                                    <h3>Quick Links</h3>
                                    <ul class="list-unstyled">
                                        <li><a href="/Home/Index">Home</a></li>
                                        <li><a href="/About/Index">About</a></li>
                                        <li><a href="/Contact/Index">Contact</a></li>
                                    </ul>
                                </div>

                                @Html.Action("FooterAccounts", "Layout")
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <p class="small">
                            &copy; @DateTime.Now.Year | Develop by <a href="https://www.ahmetyazbulursun.com" target="_blank" rel="noreferrer">Ahmet Hakan Eroglu</a>.
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- END footer -->

    </div>

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214" /></svg></div>

    <script src="~/Templates/template/js/jquery-3.2.1.min.js"></script>
    <script src="~/Templates/template/js/jquery-migrate-3.0.0.js"></script>
    <script src="~/Templates/template/js/popper.min.js"></script>
    <script src="~/Templates/template/js/bootstrap.min.js"></script>
    <script src="~/Templates/template/js/owl.carousel.min.js"></script>
    <script src="~/Templates/template/js/jquery.waypoints.min.js"></script>
    <script src="~/Templates/template/js/jquery.stellar.min.js"></script>


    <script src="~/Templates/template/js/main.js"></script>
</body>
</html>